### ISSUE TITLE
🧑🏻‍⚖️ Legal issue

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [protunner/Ryzentosh-nitro-5-an515-43-r59w#1]
# ChefKiss 

## Prelude
NootedRed license terms violated; lack of credit, copyright notice and license retention.

## Main text

I henceforth am legally obligated to request that you retain the license and follow its terms or take down this repo.

Failure to do so will require legal pursuit to retain copyrights.

**Comment by VisualEhrmanntraut** [comment]
Addendum 1: You may also proceed to removal of the infringing content.

**Comment by protunner** [comment]
> # ChefKiss 
> 
> ## Prelude
> NootedRed license terms violated; lack of credit, copyright notice and license retention.
> 
> ## Main text
> 
> I henceforth am legally obligated to request that you retain the license and follow its terms or take down this repo.
> 
> Failure to do so will require legal pursuit to retain copyrights.

I Sorry i forgot to do i gonna chance this..

**Comment by protunner** [comment]
> Addendum 1: You may also proceed to removal of the infringing content.

I deleted the files, what can i do to share without makes any ilegal thing?

**Comment by VisualEhrmanntraut** [comment]
As explained in section "Main Text", sharing the code or binaries of the NootedRed project requires the copyright notice and license retained (and its terms followed). This can be achieved by

1. Licensing the entire repository with the same `Thou Shalt Not Profit version 1.5` license,
2. adding the project licensing notice in the README, along with,
3. adding an explicit and visible mention and link to the NootedRed project.

or

1. Keep the file removed, and,
2. add instructions on how to get the NootedRed binary manually.

Do note that even if your distribution of the file is no longer against the law, you will still be frowned upon by the hackintosh community for sharing a prebuilt EFI.

**Comment by protunner** [comment]
> As explained in section "Main Text", sharing the code or binaries of the NootedRed project requires the copyright notice and license retained (and its terms followed). This can be achieved by
> 
> 1. Licensing the entire repository with the same `Thou Shalt Not Profit version 1.5` license,
> 2. adding the project licensing notice in the README, along with,
> 3. adding an explicit and visible mention and link to the NootedRed project.
> 
> or
> 
> 1. Keep the file removed, and,
> 2. add instructions on how to get the NootedRed binary manually.
> 
> Do note that even if your distribution of the file is no longer against the law, you will still be frowned upon by the hackintosh community for sharing a prebuilt EFI.

Thanks, there is a example about How to do the number 2 of licensing notice in readme(new about Github thing)

**Comment by protunner** [comment]
> As explained in section "Main Text", sharing the code or binaries of the NootedRed project requires the copyright notice and license retained (and its terms followed). This can be achieved by
> 
> 1. Licensing the entire repository with the same `Thou Shalt Not Profit version 1.5` license,
> 2. adding the project licensing notice in the README, along with,
> 3. adding an explicit and visible mention and link to the NootedRed project.
> 
> or
> 
> 1. Keep the file removed, and,
> 2. add instructions on how to get the NootedRed binary manually.
> 
> Do note that even if your distribution of the file is no longer against the law, you will still be frowned upon by the hackintosh community for sharing a prebuilt EFI.

i doesn't know if its right now but , can i put the file now?

**Comment by VisualEhrmanntraut** [comment]
No; you have to do all of the steps in the first part in order to be able to distribute the file. It is very obvious that these are not different suggestions but two paths with their own steps
